[project]
name = "mpt"
version = "0.1.0"
description = "Ethereum Merkle Patricia"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["ethereum"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
