[package]
name = "keth"
version.workspace = true
edition.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
rust-version.workspace = true
exclude.workspace = true

[dependencies]
#Alloy
alloy-genesis = { version = "0.1.2", default-features = false }

# Kakarot
kakarot-node.workspace = true

# Reth
reth-db = { git = "https://github.com/paradigmxyz/reth.git" }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth.git" }
reth-cli-runner = { git = "https://github.com/paradigmxyz/reth.git" }
reth-node-builder.workspace = true
reth-node-core = { git = "https://github.com/paradigmxyz/reth.git" }
reth-primitives.workspace = true

# Tracing
tracing = { version = "0.1.40", default-features = false }
tracing-subscriber = { version = "0.3.18", default-features = false }

# Other
clap = { version = "4.5.9", features = ["derive"] }

[lints]
workspace = true
